# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Detect rows that are (within tolerance) identical
#' @name near_dist
#' @description This function takes a numeric matrix and runs a pairwise comparison
#' of rows, reporting whether they are identical or not, with a tolerance for small differences.
#' 
#' @param k Numeric vector
#' @param tolerance The tolerance for comparing values.
#' @return A distance object containing TRUE for rows that are identical (within tolerance), false otherwise
#' @export
near_dist_cpp <- function(k, tolerance) {
    .Call(`_twopointzerothree_near_dist_cpp`, k, tolerance)
}

